### ISSUE TITLE
Graph padding

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_experiment#138]
In some graphs -- most commonly noticed if there's an outlier at position 0 -- it's hard to see what's going on. I wonder if we should take a leaf from Rebecca's book and add internal padding to the graphs?

**Comment by snim2** [comment]
Yes, I agree.

**Comment by snim2** [comment]
This seems to be the API call we need:

http://matplotlib.org/api/axes_api.html#matplotlib.axes.Axes.margins

**Comment by snim2** [comment]
Or this: http://stackoverflow.com/a/23566364/342327

**Comment by ltratt** [comment]
Why don't we try a few out and see which we think is most aesthetically pleasing?
