### ISSUE TITLE
Add  GC time and compilation time to plots.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#163]
As discussed before, we need to add two more lines to our graphs, one for GC time, one for compilation time.

If we add these on top of the graph we have, I suspect the graph will be too busy.

One idea is to use a vertical stack of 5 axes, one for each data point, a bit like this:

![subplots_demo_03](https://cloud.githubusercontent.com/assets/604955/18707792/9560c330-7fef-11e6-9b1e-1b4a109dc610.png)

Each of the axes is a subplot created with `sharex=true`.

The problem is, one figure can have only one set of subplots. Ideally we would need a way to put many figures on one page. If we can't find a way to do that in matplotlib itself, we could generate a PDF externally using tex, or even make a HTML page. This would however break the interactive mode the script currently has.

I'm open to new ideas too. It seems multi-dimensional data visualisation is hard.

**Comment by vext01** [comment]
I think a less painful approach would be to do the following:

For each process execution have two graphs:
- Graph 1: Shows WCT, cycles, amperf ration.
- Graph 2: Shows WCT, gc time, compile time.

Place each pair in the subplot grid such that graph 1 is above graph 2.

Thoughts?

**Comment by snim2** [comment]
In progress on #162 

Do we have data for GC events and compile time yet?

**Comment by snim2** [comment]
This is currently waiting on the data that we are collecting on B2.
