### ISSUE TITLE
Add net down/up functionality.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#164]
Add PRE/POST hooks to bring down the network during benchmarking.

**Comment by snim2** [comment]
@vext01 Should this be on Krun?

**Comment by ltratt** [comment]
No, it's a user config thing.

**Comment by ltratt** [comment]
Which Edd and I got working (on Linux, at least) last week, so I think we can close this issue now Edd?

**Comment by vext01** [comment]
The PR which implements this should close the issue.

**Comment by ltratt** [comment]
OK.

**Comment by ltratt** [comment]
This is is related to https://github.com/softdevteam/krun/issues/213

**Comment by vext01** [comment]
This is done.
