### ISSUE TITLE
Inconsistent filenames in patches directory

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_experiment#172]
The filenames are of the form `X.diff` and `X.patch`. I don't mind which we use, but I think it would be good to consistent to avoid confusion from casual readers. Any thoughts?

**Comment by ltratt** [comment]
@vext01 Would like to know your opinion on this though.

**Comment by vext01** [comment]
I tend to use `diff`.

**Comment by ltratt** [comment]
OK, diff it is.

**Comment by snim2** [comment]
Closed via #193
