### ISSUE TITLE
Graph plotter uses a generic name and wipes over old files

### ISSUE THREAD

**Issue by ltratt** [softdevteam/warmup_experiment#185]
At the moment, running `plot_krun_results` always creates a filed called `krun_results.pdf`, happily overwriting what was there before. I think we need to choose one or the other: either use a less generic name or prevent overwriting (both is overkill IMHO). My preference would be for the former, so that `plot_krun_results x.y.json.bz2` would create a file `x.y.pdf`.

**Comment by snim2** [comment]
`krun_results.pdf` is the default name. To choose your own name on the command line, pass in a `-o` option:

`./bin/plot_krun_results -o myfilename.pdf results.json.bz2`

**Comment by ltratt** [comment]
Generic names aren't a good idea: either let's say "you have to specify the output filename" or choose a less generic name. [I'm fine with either.]

**Comment by snim2** [comment]
OK, I think the former is probably what we need, to help avoid problems in the `Makefile` (if we add charting etc. in there)

**Comment by ltratt** [comment]
Fine with me. Thanks!
