### ISSUE TITLE
New script to generate useful information from the results of the startup experiment

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#200]
We need to generate useful output from the results of the startup experiments. Our usual plots are not very useful, tables with means and confidence intervals would be more useful.

**Comment by snim2** [comment]
The values that startup places in `wallclock_times` need pre-processing, each value is a time (in seconds) since boot. To derive each VM startup time, we need to subtract the first "wallclock time" from the second.

**Comment by vext01** [comment]
I might be wrong about the time since boot. It might just be the value of the RTC. It's exact definition doesn't affect us.
