### ISSUE TITLE
Put instrumentation data in the scp tarball

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#252]
So we can use the instrumentation data before the benchmark has finished.

**Comment by ltratt** [comment]
Equally, I think we've done this one...

**Comment by vext01** [comment]
This has not yet been implemented:

```
 SCP_CMD = ("tar czf - ${KRUN_RESULTS_FILE} ${KRUN_LOG_FILE} ${KRUN_MANIFEST_FILE} | " ...
```

But come to think of it, I don't think I want this. The instrumentation data gets huge and scping it around will make the experiment take longer, and open a larger window for scp failures.

I suggest we close this.

**Comment by ltratt** [comment]
Agreed.
