### ISSUE TITLE
Fix magic numbers with --export-size

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#264]
The magic numbers we use to set font sizes, the space between plots and so on are hard-coded. Now that we allow the user to set the size of each figure, in inches, with `--export-size` the magic numbers can sometimes result in:

  * Font sizes that are too small to read
  * Font sizes that are too large, and so overlap with other artists
  * Spacing between plots that seems "too large" and wastes space
  * Spacing between plots that is so small that some artists overlap

**Comment by ltratt** [comment]
As a quick fix, can I suggest we just scale these relative to the "export size"? So let's say the original size was 10x10. If someone specifies 20x20, we just double the magic numbers. With luck we won't need to do anything more complex!

**Comment by snim2** [comment]
We can have a go. I was hoping @vext01 might have a clever idea here?

**Comment by vext01** [comment]
Sadly, I don't. Although Laurie's idea is sound, I've worked with matplotlib enough to know that it probably won't work as we expect.

**Comment by snim2** [comment]
Do we actually need --export-size or can we go back to pre-computing the figure sizes?

**Comment by vext01** [comment]
What do you mean by "pre-computing the figure sizes"?

**Comment by snim2** [comment]
We used to precompute the figure size, based on how many plots were in each stack. We used to have a larger figure size if we had more plots in the stack. 

I wasn't entirely clear why `--export-size` was introduced, but my vague understanding is that it was to allow the user to have the same figure size no matter how many plots are in the stack. In which case, I'm not sure why we pass that back to the user, rather than removing the bit of arithmetic that used to calculate the figure size.

**Comment by vext01** [comment]
I see. So I think what you are saying is that the size of the individual plots should be configurable?

**Comment by snim2** [comment]
No, I am saying that the user should not be able to configure anything.

**Comment by vext01** [comment]
You would just zoom in on the PDF if you wanted to see it larger?

**Comment by vext01** [comment]
I'm actually OK with this, as long as the sizes are hackable constants at the top of the file.

**Comment by snim2** [comment]
I didn't realise that allowing the user to "zoom in" was the intention of this feature. Was this a stop-gap until we fixed #191 ?

**Comment by vext01** [comment]
I'm just trying to cover all cases, but perhaps I am going overboard. If you think what you are proposing fixes our issues then go ahead. And sorry for introducing --export-size.

**Comment by snim2** [comment]
It seems that we do need the `--export-size` CLI switch (see comments on #266) and the magic numbers don't appear to be much of a problem. If they become a problem in future it would be best to open a new issue with steps to replicate.
