### ISSUE TITLE
Improve inset placements

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#291]
Our recent testing uncovered a case where insets are drawn over data (page one only):

[inset_test_case.pdf](https://github.com/softdevteam/warmup_experiment/files/670636/inset_test_case.pdf)

**Comment by ltratt** [comment]
Yes, with the new data-run, this is happening quite frequently. The problem *seems* to be that in cases where there probably isn't room for an inset (or, at least, the inset needs to be smaller than normal), the inset is just plonked somewhere. I wonder if the "ah, there's nowhere the inset can go" logic is a bit wrong somehow? Another alternative explanation is that the inset logic isn't taking into account the size of the axes on the inset.
