### ISSUE TITLE
use slightly better checksumming

### ISSUE THREAD

**Issue by cfbolz** [softdevteam/warmup_experiment#33]
The current checksumming just adds up some numbers. That has the problem that some re-ordered computation is not caught ever. It would be better to do something like this:

`checksum = (1000003 * checksum) ^ new_info;`

That catches reorders too (it's the way Python strings and tuples are hashed).

**Comment by vext01** [comment]
Can you explain more how this detects re-orders? And why is re-ordered computation bad? As long as the result is the same, I'm happy for the compiler to re-order things. Or no?

**Comment by ltratt** [comment]
Edd's kinda right in the sense that the compiler can validly statically move things around. One would expect this to be deterministic from compile to compile, though I suppose it doesn't have to be (and the more general non-determinism checks that CF is doing will check that really is the case). Put another way, I don't think we should expect _too_ much from the above check, nor should we worry too much about that.

**Comment by ltratt** [comment]
Is this still active or should we close it?

**Comment by cfbolz** [comment]
since nobody apart from me ever liked the idea, we can close it.
