### ISSUE TITLE
Minor octane glitch on OpenBSD

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#334]
```
bench-octane: build-krun build-vms
	PYTHONPATH=krun/ LD_LIBRARY_PATH=${GCC_LIB_DIR}:${LIBKRUN_DIR} ${PYTHON} extbench/runoctane.py
	bin/csv_to_krun_json -u "`uname -a`" -v V8 -l JavaScript octane.v8.results
	bin/csv_to_krun_json -u "`uname -a`" -v SpiderMonkey -l JavaScript octane.spidermonkey.results
```

The last line crashes on OpenBSD as we skip spidermonkey there, My initial instinct was to kill these conversion lines altogether, since we can use our shiny new frontend to abstract these details (and the other script invocations this target fails to run) away. However is it useful to have the `-u` and `-v` filled in automatically.

Shall we make a new target which runs the new frontend (passing the right uname etc) to make the all of the possible outputs (tables, html, plots...)?

**Comment by ltratt** [comment]
Even if we use the new front-end, won't we need some sort "if not OpenBSD" construct in the makefile?

**Comment by vext01** [comment]
You're right. So there's actually two issues here:

 * Don't try to use data which may not exist.
 * Take an "all or nothing" approach to running scripts for the user.

The first I would fix with simply only using the data if the file exists.

**Comment by vext01** [comment]
Any thoughts on this @snim2 @ltratt ?

**Comment by snim2** [comment]
There are a couple of issues with the Makefile; one is that we don't differentiate between machines, this is a problem for OpenBSD but the target `plot-warmup-results` is also odd, because there are really three / four files called `warmup_results.json.bz2` from the different benchers.

I was never really sure how to deal with this, but the current situation is clearly unsatisfactory.

**Comment by ltratt** [comment]
@snim2 The point of the Makefile isn't to deal with being run on multiple machines (doing that would drive us insane, and wouldn't be very useful anyway), so I don't think that we need to worry about that.

@ebarrett If we can do a sensible "only plot X if file Y exists", then that would seem to be the easiest solution.

**Comment by vext01** [comment]
Note that the current behavior is not plotting anything. It's invoking only the first step, converting the CSV to a Krun JSON file. It's not marking outliers, doing classification, making plots etc.

I really think we should do all of that stuff, or none of that stuff. Not the first step. Which do you think makes more sense?

I'm leaning toward none, and the user can then use the bin/warmup script to make whatever deliverables they want.

**Comment by snim2** [comment]
The `plot-` targets all deal with marking outliers, marking changepoints as well as plotting. The `table-` targets deal with creating tables.

**Comment by ltratt** [comment]
I don't see this as a big issue either way; at least, not enough to burn time on it before the 0.9 run. I'd suggest that we do the minimal fix that unbreaks things on OpenBSD and move on.
