### ISSUE TITLE
Run build_stats in Makefile and check table- targets

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#335]
Following the addition of the `bin/warmup-stats` script, we may need to export a few environment variables (`PATH`, `LD_LIBRARY_PATH`) in order to run the table scripts from the Makefile. We should probably be running `build_stats.sh` from the Makefile, also.

**Comment by ltratt** [comment]
We definitely shouldn't run `build_stats.sh` from the Makefile. We can run it from `build.sh` though, if we want.

**Comment by snim2** [comment]
Building tables and plots differs between experiments, we probably /don't/ want to action this (and it pre-dates the repo split).
