### ISSUE TITLE
Simplify V8 tarball creation.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#462]
A post on v8-users reveals how you are supposed to fetch an old version of the V8 src:
https://groups.google.com/forum/#!topic/v8-users/Ng3yx6zshq8

I suggest we make a new tarball via this method (the way we did it is convoluted). Since we won't be running any experiments until the servers move, over the next few days is probably a good time.

Thoughts @ltratt ?

**Comment by vext01** [comment]
Don't forget this one @ltratt.

**Comment by ltratt** [comment]
When you say "make a new tarball" do you mean "make and host a tarball"?

**Comment by vext01** [comment]
Correct. There's code in the warmup repo to make a tarball, but it's convoluted.

**Comment by ltratt** [comment]
That's not quite answered my question :) Do we even need to host a tarball? That mailing list post suggests we'll always be able to get to a known state by doing a checkout.

**Comment by vext01** [comment]
I suggest we do make a tarball since:
 a) then we are immune from `depot_tools` breakage.
 b) there is no confusion as to whether there may be a moving target.
 c) depot_tools doesn't work on openbsd, and patching isn't easy as depot_tools always updates itself.
