### ISSUE TITLE
Graal-related config file crash on OpenBSD.

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#53]
http://pastebin.com/fyM4MY2A
- The error message needs to be better.
- Graal should not be benchmarked on OpenBSD. Add a guard in config file.

**Comment by vext01** [comment]
Sorry assigned the wrong person. Meant to assign myself.

**Comment by ltratt** [comment]
:)

**Comment by vext01** [comment]
This is fixed.
