### ISSUE TITLE
wrong timer used on jruby

### ISSUE THREAD

**Issue by cfbolz** [softdevteam/warmup_experiment#55]
the Ruby runner contains this code:

```
if /linux/ =~ RUBY_PLATFORM
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC_RAW
else
    MONOTONIC_CLOCK = Process::CLOCK_MONOTONIC
end
```

however, on JRuby `RUBY_PLATFORM` is "java", thus the wrong timer is used. Here is a discussion how to fix this: https://www.ruby-forum.com/topic/150942

**Comment by cfbolz** [comment]
I might try to fix this later, but want to do some startup cleanup first

**Comment by vext01** [comment]
I'm going to move this issue to the krun repo.

**Comment by vext01** [comment]
Moved here: https://github.com/softdevteam/krun/issues/95
