### ISSUE TITLE
wamup requires xzdec

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#73]
This is not very standard on Linux, so It would be nice for this to be either installed automatically or at least documented.

**Comment by snim2** [comment]
Similarly:

```
configure: error: Could not find all X11 headers (shape.h Xrender.h XTest.h Intrinsic.h). You might be able to fix this by running 'sudo apt-get install libX11-dev libxext-dev libxrender-dev libxtst-dev libxt-dev'.
```

**Comment by snim2** [comment]
And again:

```
configure: error: Could not find freetype! You might be able to fix this by running 'sudo apt-get install libfreetype6-dev'. 
```

**Comment by snim2** [comment]
And again:

```
configure: error: Could not find alsa! You might be able to fix this by running 'sudo apt-get install libasound2-dev'. 
```

**Comment by ltratt** [comment]
We can easily check for binaries, but trying to check for libraries is a Sisyphean task which it's not even worth us trying (we'd be trying to write a `configure` equivalent, which wraps up all the other VMs `configure`s!). So let's add a check for `xzdec`... but we have to acknowledge, unfortunately, that users have to go through the "I don't have that library" dance all by themselves :/

**Comment by snim2** [comment]
True, but on Debian based machines it is quite easy to just apt-get install a bunch of these. Maybe it's trickier on other systems.

**Comment by vext01** [comment]
Many projects have a command in `README.md` which can be pasted into a shell.

E.g. http://pypy.readthedocs.org/en/latest/build.html#install-build-time-dependencies

**Comment by ltratt** [comment]
The point is: we can't know which libraries people will need. They'll change not just across different OSs, but even across OS versions. Trying to install them will just send us mad.

**Comment by vext01** [comment]
I'm not suggesting that we document exhaustively all the combos, but most unixy people are running a debian derivative. Debian makes a new major release every 3 years, so it's not a fast moving target.

**Comment by ltratt** [comment]
We're not building a Debian only thing, nor do we want to suggest that it's Debian only. For one thing, we're running (albeit a subset) on OpenBSD too! And there are at last count a zillion other Linux distros that aren't Debian, several of which are more popular than Debian.

I'm happy for someone to do a PR that checks for the xzdec binary in build.sh. But checking for libraries is a definite no -- we have way better things to do with our time.

**Comment by vext01** [comment]
Seems to be some confusion. I'm suggesting we list what is required in `README.md`.

**Comment by ltratt** [comment]
No, because we don't know what's required accurately! For example, alsa isn't required on OpenBSD. Any attempt we make will be an approximation, at best accurate on a single OS version, and maybe not even then. This is a really, really hard problem and an endless time sink. Let's not even bother pretending we can solve it.

**Comment by snim2** [comment]
I think we can document the binaries that our scripts explicitly invoke, at least. Things the VM makefiles invoke I agree, is probably a reach.

**Comment by ltratt** [comment]
Even binaries is surprisingly hard, as configure scripts often do things like `if os == X then binary1`. If we're not careful, we'll end up forcing people on OS Y to install packages they won't actually use.

**Comment by vext01** [comment]
I disagree, but I don't think Laurie is likely to budge on this. So users are on their own when it comes to building the experiment.

**Comment by ltratt** [comment]
To avoid ambiguity, I think build.sh should explicitly check for the existence of all binaries it invokes directly. But if one of the VMs needs another binary, we should leave it to that VM to do so.

If we wanted to be super-clever -- but I don't think this is worth the effort either -- we could run all the configure scripts in one go up front, before building each VM.
