### ISSUE TITLE
[new_charts] refactor outer loop

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#81]
As mentioned previously, if you pass a non-existing key to the plotting script's `-b`, then no graphs are processed.

Before we fix this, I recommend refactoring the outer loops, otherwise we have to apply a hack twice.

**Comment by snim2** [comment]
I'm not totally convinced that merging the loops makes sense. In order to produce the large PDF the `with PdfPages(outfile) as pdf:` must be around the calls to `savefig()`...

**Comment by vext01** [comment]
We don't have to use the context manager if we don't want to. You can probably do something like:

```
if not interactive:
    pdf = PdfPages(outfile)

... common logic

if not interactive:
    pdf.close()
```

The script should certainly bomb out if the key passed to `-b` is a typo -- i.e. that isn't a key that appears in the json file at all.

**Comment by vext01** [comment]
Fixed
