### ISSUE TITLE
[new_charts] Font sizes

### ISSUE THREAD

**Issue by vext01** [softdevteam/warmup_experiment#82]
@snim2, what do you think of the current font size of graphs when imported into the paper:

![toosmall](https://cloud.githubusercontent.com/assets/604955/12268682/b4d62636-b945-11e5-88e1-eecbb90c4320.png)

I think they are a little too small?

**Comment by ltratt** [comment]
This may suggest the graphs are also too small? After all, if the figure stays at that scale, and we increase the iteration fonts by the same amount, we'll probably only have room for "0, 500, 1000".

**Comment by ltratt** [comment]
(Which implicitly suggests the lines in the graph are teeny)

**Comment by vext01** [comment]
The size of the graph shouldn't matter, as it's a vector format, right? I think what matters is the relative size of the fonts to the rest of the graph.

If you don't specify a scale in TeX, then the graph consumes 3/4 of a page without looking pixelated.

**Comment by ltratt** [comment]
They might be vector formats, but human eyes still struggle to see such tiny things properly. Or, if I interpret your argument literally, if we make the graphs 1 inch square on the page, they'll still be printed correctly (dpis are high enough)... but would we able to see any useful detail? ;)

**Comment by vext01** [comment]
Do you agree that the font on the axes needs to appear larger to be readable? I can make that happen.

**Comment by ltratt** [comment]
My point is: if you make the graph bigger on the page, the fonts will also get bigger.

**Comment by snim2** [comment]
This was why we wanted to try tikz - so the font size would be determined by the LaTeX file and not hard coded into a bitmap image. Getting that working would be tricky, but if this is still a problem I will resurrect the tikz stuff once the first draft is in.

**Comment by vext01** [comment]
We have worked around this by using lipics paper style, which allows larger figures. Closing.
