### ISSUE TITLE
Enable user place specific process executions of a number of benchmarks on a single axis

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#89]
Sometimes it is useful to compare several individual executions of different benchmarks. E.g. 
- Fannkuch Redux, Hotspot, Process execution 1
- Fannkuch Redux, Hotspot, Process execution 2
- Fasta, PyPy, Process execution 1
- Fasta, PyPy, Process execution 1

This does not make sense unless all four run sequences are charted with the same y-limits.  This should work even if the selected process executions come from different Krun results files.

/cc @vext01

**Comment by vext01** [comment]
Raised via a comment from @cfbolz in the warmup paper draft.
