### ISSUE TITLE
Consider some corner cases

### ISSUE THREAD

**Issue by snim2** [softdevteam/warmup_experiment#95]
At the moment we generally assume that Krun results files contain results from different machines. There is nothing to stop someone running a few process iterations and dumping a results file, then running a few more and dumping another file. In this case, the same machine will have collected results for the same benchmark in two separate files. 

It isn't immediately clear how the process executions should be numbered in this case (or whether it matters) and it is possible that the current version of the script will overwrite some values. 

We should make a test case for this (and we need more automated testing in general), and make it clear to the user how the data has been processed. Alternatively, we could decide that this is not a legitimate use of the script, and instead provide another script to merge two Krun results files.

**Comment by ltratt** [comment]
Why would someone remove the initial results file? If they copy it, but don't delete it, Krun will keep appending to it as expected I think?

**Comment by snim2** [comment]
Actually this is correct, Krun will append to an existing file if you are resuming a session, or it will complain if a results file already exists. However, the question is should charting two separate Krun results files from the same machine be verboten?

**Comment by ltratt** [comment]
OK. Since it's therefore a silly thing for someone to do, I don't think we should bother handling it. If you're OK with that, I suggest we close this issue.

**Comment by snim2** [comment]
In that case, I would rather leave this open and have the plotting script emit an error message.

**Comment by ltratt** [comment]
OK, though I think this the lowest of low priority ;)

**Comment by vext01** [comment]
This is a krun issue, right? Not a warmup experiment issue?

**Comment by ltratt** [comment]
I'd be happy to close it (I don't think it's worth our time worrying about the infinite number of silly things users might possibly do).

**Comment by vext01** [comment]
@snim2 happy with this resolution?

**Comment by snim2** [comment]
@vext01 sure.
