### ISSUE TITLE
point to branch trace-variants in README

### ISSUE THREAD

**Issue by cfbolz** [softdevteam/warmup_experiment#98]
we should point that branch out before we bundle the source code.

**Comment by ltratt** [comment]
Has this been handled? Did we decide to do things as a directory rather than a branch?

**Comment by vext01** [comment]
I don't mind where these variants live, but I'm happy to make the change.

**Comment by ltratt** [comment]
I think we should make them easily accessible. When we distribute a source tar ball, there won't even be a branch that they can switch to / from.

**Comment by vext01** [comment]
I'm OK with that, but incase it makes any difference, since source code size is no object anymore, the last round of source tarballs I made did contain all VCS metadata.

**Comment by ltratt** [comment]
OK, fair enough. But, even given that, I think they should be in a top-level dir that people can't miss.

**Comment by vext01** [comment]
Works for me. PR  coming soon.

**Comment by vext01** [comment]
This is done.
